### Lambda:
A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

Syntax: 

lambda arguments : expression

The expression is executed and the result is returned:

In [6]:
# Example 1a:
# Syntax: 
# lambda a: expression 

a = lambda c: c*5

print(a(4))

20


In [7]:
# Example 1b: the argument or parameter is given a value at the print statement

y = lambda a: a + 15
print(y(20))

35


In [8]:
# Example 2: It can take more than one argument

a = lambda b,c: b*c

print(a(4,3))

12


In [9]:
# Example 3
c = lambda x,y,z: x+y+z

print(c(5,6,7))

18


Why use Lambda functions?

The power of lambda is better shown when you use them as an anonymous function inside another function.

Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

In [10]:
def multi_num(a):
    return lambda x:x*a
times = multi_num(5)

print(multi_num(5)(4)) # another option/alternative, line 3 may not be necessary

print(times(4))
print(times(10))
print(times(20))

20
20
50
100


In [10]:
def myfunc(n):
  return lambda a : a * n
# Use that function definition to make a function that always doubles the number you send in:
doubler = myfunc(2)

print(doubler(10))

# what happens here is that a variable is created bcos return is used and then when you print
# the variable name, you will give s value for the lambda as it is in the normal syntax

20


In [11]:
def myfunc_2(x):
    return lambda b: b*x

tripler = myfunc_2(3)

print(myfunc_2(3)(10))

print(tripler(10))

30
30


In [19]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)
my4 = myfunc(4)

print(mydoubler(5))
print(mytripler(5))
print(my4(5))

10
15
20


### Arrays: An array is also a data structure that stores a collection of items. Like lists, arrays are ordered, mutable, enclosed in square brackets, and able to store non-unique items. To use arrays in Python, you need to import either an array module or a NumPy package.

import array as arr

import numpy as np

Syntax: arrayName = array(typecode, [Initializers]) OR np.array([elements]) 

Typecode are the codes that are used to define the type of value the array will hold. Some common typecodes used are:

Typecode	      Value

b	Represents signed integer of size 1 byte/td>

B	Represents unsigned integer of size 1 byte

c	Represents character of size 1 byte

i	Represents signed integer of size 2 bytes

I	Represents unsigned integer of size 2 bytes

f	Represents floating point of size 4 bytes

d	Represents floating point of size 8 bytes

In [12]:
from array import *
import array as arr 
import numpy as np 

In [16]:
a = array('i',[15, 16, 19, 20])

print(a)

array('i', [15, 16, 19, 20])


In [67]:
array1 = array('i', [1,2,3,4,5])

print(array1)

array('i', [1, 2, 3, 4, 5])


In [14]:
b = np.array([50, 60, 100, 200])

print(b)

[ 50  60 100 200]


In [23]:
# OR

array_one = np.array([10, 20, 30, 40, 50])

print(array_one)

print (array2[0])

print (array2[2])

print(array2[-4])

print(array2[:4])

[10 20 30 40 50]
10
30
20
array('i', [10, 20, 30, 40])


In [20]:
# Accessing array elemets: indexing 

array2 = array('i', [10,20,30,40,50])

print (array2[0])

print (array2[2])

print(array2[-4])

print(array2[4:])

10
30
20
array('i', [50])


In [69]:
months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array)
print(months_array[3])


['Jan' 'Feb' 'March' 'Apr' 'May']
Apr


In [25]:
# Adding elements to array: you use insert() and you quote the index number and new element 
# to be added 

array3 = array('i', [10,20,30,40,50])

array3.insert(1,60)

for x in array3:
    print(x)

10
60
20
30
40
50


In [26]:
a = [1, 2, 3,  4]
b = [10, 20, 30, 40]

print(a + b)

[1, 2, 3, 4, 10, 20, 30, 40]


In [27]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A + array_B)

# See the result! It is because numpy is numerical python and it is known for doing calculations
# in python, so it doesm't see the + as concatenation, but an addition. 

[5 7 9]


In [57]:
# Removing elements from array 

array4 = array('i', [10,20,30,40,50])

array4.remove(40)

for x in array4:
    print(x)

10
20
30
50


In [58]:
# Searching for elements: using the index() method

array5 = array('i', [10,20,30,40,50])

print (array5.index(40))

3


In [88]:
# Update elements

array6 = array('i', [100,205,305,400,505])

array6[2] = 800

for x in array6:
 print(x)

100
205
800
400
505


In [28]:
array_1 = np.array([5, 10, 15, 20])

div = array_1/3

print(div)

[1.66666667 3.33333333 5.         6.66666667]


In [29]:
x = [5, 10, 15, 20]
y = x/3
print(y)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [72]:
# Other calculations in array 

array_new = np.array([3, 6, 9, 12])

division = array_new/3
print(division)
#print (type(division))

[1. 2. 3. 4.]


In [76]:
# You can't do that with lists, see example below;
a = [2, 4, 6, 8]
b = a/2

print(b)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### 2-D arrays:

Two dimensional array is an array within an array. It is an array of arrays. In this type of array the position of a data element is referred by two indices instead of one. So it represents a table with rows and columns of data. In the example below of a two dimensional array, observe that each array element itself is also an array.

Consider the example of recording temperatures 4 times a day, every day. Such data for 4 days can be presented as a two dimensional array as below.

In [33]:
# Day 1 - 11 12 5 2 
# Day 2 - 15 6 10 
# Day 3 - 10 8 12 5 
# Day 4 - 12 15 8 6 

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

#T[0][2]
T[2][3]



5

The data elements in two dimesnional arrays can be accessed using two indices. One index referring to the main or parent array and another index referring to the position of the data element in the inner array. If we mention only one index then the entire inner array is printed for that index position. The example below illustrates how it works.

In [79]:
T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

print(T[0])

print(T[1][2])
print(T[0][3])

[11, 12, 5, 2]
10
2


In [36]:
T

[[11, 12, 5, 2], [15, 6, 10], [10, 8, 12, 5], [12, 15, 8, 6]]

In [35]:
for r in T:
    for c in r:
        
#         print(c, end=' ') #end=' ' is used as space instead of a new line
        

[11, 12, 5, 2]
[11, 12, 5, 2]
[11, 12, 5, 2]
[11, 12, 5, 2]
[15, 6, 10]
[15, 6, 10]
[15, 6, 10]
[10, 8, 12, 5]
[10, 8, 12, 5]
[10, 8, 12, 5]
[10, 8, 12, 5]
[12, 15, 8, 6]
[12, 15, 8, 6]
[12, 15, 8, 6]
[12, 15, 8, 6]


In [41]:
for r in T:
    print(r, end=' ')

[11, 12, 5, 2] [15, 6, 10] [10, 8, 12, 5] [12, 15, 8, 6] 

In [1]:
print('You can start coding \neveryday')

You can start coding 
everyday
